### PR TITLE
lodash _.first doesn't return an array

### PR DESCRIPTION
**Pull request by jebeck**
I believe this addresses both bugs recently found on staging: https://trello.com/c/2I11ddBi and https://trello.com/c/0zfGV7oG.

The issue is that `_.first` does not return an array, and we were trying to extract from it at index 0. Possibly/probably(?) this is a change in lodash and came in with the dependency updates.

Ping @kentquirk

### CODE REVIEW

**Comment by jebeck** [comment]
Updated this, ping @kentquirk @jh-bate 

To run the regression test, you have to switch to node 0.10.x and either clear and reinstall the dependencies or do an `npm rebuild`.

**Comment by kentquirk** [comment]
I don't know how this is going to work if travis is set up to run tests against v0.12 (which it is). Also, how useful is it, really, to specify that we're using v0.12 but our tests have to run against v0.10? It doesn't really give us confidence in either the positive or negative cases.

**Comment by jh-bate** [comment]
Yeah I think we have realised its potentially of minimal use at this stage with the whole jest and lack of v0.12 support. I also invested sometime with the terms and conditions to do tests - I think at this stage we will add the tests for 'documentation' and then have to either switch test framework or see if jest updates in the near future. Either way its a bit crap :(

**Comment by jebeck** [comment]
Yeah, I didn't realize that the situation was as problematic as it is. But hey, now we know. I'm going to sign up for updates to the Jest repo and we can just see how it plays out in the next month or so. If they (or someone else who's desperate for the update) update it to get it to work with 0.12, then we can try to expand the tests. If not, we'll start thinking about other solutions.

**Comment by jh-bate** [comment]
LGTM - test framework will have to wait

**Pull request merged**
