### PR TITLE
prep for playing nice w/new viz repo

### PR DESCRIPTION
**Pull request by jebeck**
Misc updates, including:
- from React 0.14 to React 15
- from Babel 5 to Babel 6 (major API changes)

Note that we'll have to test the Babel polyfill for `Object.assign` on IE 11 again because the Babel update necessarily involved an update to how we polyfill that...

Depends on [tideline #283](https://github.com/tidepool-org/tideline/pull/283) as well.

### CODE REVIEW

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;icRNVum8&#x2F;21-blip-tideline-update-dependencies-in-repos-to-play-nice-with-the-new-viz-repo"> [blip] [tideline] update dependencies in repos to play nice with the new viz repo</a>

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;AMRR0T4w&#x2F;2-ux-0-dev-1-tst-2-blip-cgm-in-trends-object-assign-error-in-blip"> &lt;ux:0 dev:1 tst:2&gt; [blip] [cgm in trends] Object.assign error in blip</a>

**Comment by jebeck** [comment]
Ping @krystophv or @jh-bate for review. Depends on [tideline #283](https://github.com/tidepool-org/tideline/pull/283). The issue with the polyfill for `Object.assign` in IE 11 and below turned out to be quite a simple oversight in the webpack config (in 24c8343e88bb9b72a565cbc939e6fcf4ad5e1224). Again, probably best to sign off if all looks good and then let me coordinate merges later as we get closer to getting CGM in trends to prod. (I do want to get these pure deps updates to prod _first_ but given priorities we need to let @krystophv's #319 go through to prod first.)

**Comment by jebeck** [comment]
@krystophv can you give this a last sign-off, with particular attention to looking for the most recent tweaks you made? I ran into some merge conflicts that I didn't resolve quite right the first time around, so then it got quite confusing, unfortunately. I want to make sure I don't bork anything you just worked on!

(I did purposely delete the verificationwithpassword test focused on the React warnings because with the update to 13.x I had to delete that style of test everywhere and keep only the ones where we check that we have no warnings when we provide the required props.)

**Comment by krystophv** [comment]
This LGTM. All the recent edits have been preserved through the merge(s). 👍

**Pull request merged**
