### PR TITLE
port smbg version of trends view to viz repo

### PR DESCRIPTION
**Pull request by jebeck**

### CODE REVIEW

**Comment by jebeck** [comment]
[[viz] port smbg version of trends view to viz repo](https://trello.com/c/35wkckjP/1-viz-port-smbg-version-of-trends-view-to-viz-repo)

**Comment by krystophv** [comment]
@jebeck - can the status of this PR be upgraded to "ready for review"?

**Comment by krystophv** [comment]
@hntrdglss - would you be available to review this?

**Comment by hntrdglss** [comment]
@krystophv Certainly!

**Comment by jebeck** [comment]
@krystophv you need to version bump tideline because @jh-bate forgot to merge #368 until I pointed it out just now, and this branch is out of date on it. So do another update from master please.

**Pull request merged**
