### PR TITLE
Release v1.72.0 to master

### PR DESCRIPTION
**Pull request by clintonium-119**
Release v1.72.0 to master

### CODE REVIEW

**Comment by clintonium-119** [comment]
@krystophv Can you please review [this commit](https://github.com/tidepool-org/blip/pull/1319/commits/77e3634c6c93e770e78f73a1e79ab1e24059987e)?
I had meant to push it to a new PR branch, but pushed directly to the release candidate accidentally.

It resolves a bug that was had the launchDarkly clinic context not being set on login/refresh if the user had a pending clinic invite.  See [WEB-2713]

**Comment by krystophv** [comment]
@clintonium-119 commit diff LGTM 👍🏼

**Pull request merged**
