### PR TITLE
[WEB-1440] Route redirect hotfixes

### PR DESCRIPTION
**Pull request by clintonium-119**
See [WEB-1440] for details.

[WEB-1440]: https://tidepool.atlassian.net/browse/WEB-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by krystophv — CHANGES_REQUESTED** [review]
Largely LGTM, just one dropped/ignored error that it may be best to return early on. If there's justification for ignoring it, feel free to just comment as such and re-request review 👍🏼

**Comment by clintonium-119** [comment]
I've updated the Auth routes gate to return early for user and clinics fetch errors.  

Also, I noticed an issue where I needed to ensure that when we submit the confirmation modal without having triggered a previous submission via the clinician profile or clinic details forms, the `submitting` state was set to true so that the forced logout would occur (otherwise it would navigate on to the workspaces page before the logout timeout resolves).

**Review by krystophv — APPROVED** [review]
LGTM 🚢

**Pull request merged**
