### PR TITLE
two-tone color scheme for trends view days of the week

### PR DESCRIPTION
**Pull request by jebeck**
In conjunction with [tideline PR #197](https://github.com/tidepool-org/tideline/pull/197). That should be merged and tagged first, then this PR updated.

At present, the sub-navigation for selecting and deselecting days of the week - in particular, the dark text for weekday abbrevs on the darker turquoise - does not meet our accessibility requirements for text contrast:
screenshot 2015-01-12 15 33 50

I attempted a quick solution (make the day of week text white for weekdays), but I don't think it works very well:
screenshot 2015-01-12 15 38 20
(White text on the weekend color also fails our accessibility requirements.)

Further input required to move forward... Ping @skrugman @brandonarbiter

### CODE REVIEW

**Comment by skrugman** [comment]
Can you try the darkest grey (near black) on the weekdays? The different
color for weekend and weekday texts is confusing I think.

*Sara Krugman *
Lead designer

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.

*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by jebeck** [comment]
@skrugman it's already at #636363, which appears to be the darkest in the blip CSS as far as I can tell.

It has to be at least #353535 to pass. I can add that color if you like.
Screenshot:
screenshot 2015-01-12 15 58 00

**Comment by skrugman** [comment]
That works - In general we are trying to go with more contrast, and in a
further revision/UI debt card i have I moved to a very dark purple #81946
for navigation - does that pass accessibility?

*Sara Krugman *
Lead designer

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.

*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by jebeck** [comment]
Whether your very dark purple passes depends on the background color @skrugman (I dunno whether you're still talking about the day selectors for trends view...?)

The contrast checker is here: http://webaim.org/resources/contrastchecker/

Reminder: our guidelines are to meet WCAG at the AA level. Text has to be at least 14px to count as "large".

I will commit the darker color and push it up into this PR.

**Comment by skrugman** [comment]
Sorry yeah. It does pass. Use that if you haven't already pushed it.

*Sara Krugman *
Lead designer

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.

*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by jebeck** [comment]
I already pushed, but it's easy to change. However, #81946 isn't enough digits @skrugman...?

**Comment by skrugman** [comment]
(tired...) it is this - #281946

*Sara Krugman *
Lead designer

*Tidepool *An open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.

*Phone :* 617 549 1483
*Email : *sara@tidepool.org
*Web : *Tidepool.org <http://tidepool.org/>

**Comment by jh-bate** [comment]
LGTM - tideline dependency is merged already

**Pull request merged**
