### PR TITLE
CBG trends display selections

### PR DESCRIPTION
**Pull request by krystophv**
Use the new display toggles from `viz` and track metrics.

### CODE REVIEW

**Comment by krystophv** [comment]
[CGM Trends 1 - Add Checkboxes, default top/bottom off [dev: 5, tst: 1, ux: 1]](https://trello.com/c/SoqZj1GH/52-cgm-trends-1-add-checkboxes-default-top-bottom-off-dev-5-tst-1-ux-1)

**Comment by krystophv** [comment]
Depends on: https://github.com/tidepool-org/viz/pull/36

**Comment by krystophv** [comment]
ping @jebeck for review (or feel free to pass to next available person)

**Comment by krystophv** [comment]
@jebeck - I added tests for the tracking middleware as none previously existed. I think most of the rest of the changes are relying on having unit tests in the `viz` repo. I don't seem to be able to find any existing sets of tests that need updating. If you think it'd be a good opportunity to add in tests for the `Footer` or `Modal` components (which I don't think we have right now) then I can look into those.

**Comment by jebeck** [comment]
Tests on `Footer` would be good with the added complexity. Fine to leave `Modal` w/o tests. Thanks @krystophv!

**Comment by krystophv** [comment]
@jebeck - I think that's all the tests that needed updating/creating. This should be good for review again.

**Comment by jebeck** [comment]
Ditto here with another update from master because of the late merge of #368

**Comment by jebeck** [comment]
Thanks for the add of the totally missing tracking middleware tests!

**Pull request merged**
