### PR TITLE
modify requireAuthAndNoPatient to redirect to /terms as appropriate

### PR DESCRIPTION
**Pull request by jebeck**
During the testing of the blip w/redux RC, it was discovered that it was possible to navigate directly to /patients/new without having accepted the TOS and Privacy Policy first. Here is the fix, including regression tests.

@GordyD review plz.

### CODE REVIEW

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rzD0Fq4v&#x2F;20-blip-bugfixes-found-during-testing"> [blip] bugfixes found during testing</a>

**Comment by GordyD** [comment]
Uh oh, Travis crashed!

**Comment by GordyD** [comment]
LGTM, apart from travis dying on `npm install`!

**Comment by jebeck** [comment]
Yeah Travis is having an issue right now installing Chrome for the integration tests. @krystophv and I believe either Google or the apt-source list need to be fixed, so this should resolve itself. Since all the (non-integration) tests are passing on Circle on node v0.12.7, I'm satisfied with that.

**Comment by GordyD** [comment]
Yea, that sounds good to me. Long live Circle! (hehe)

**Pull request merged**
