### PR TITLE
Sk/update terms

### PR DESCRIPTION
**Pull request by ursooperduper**
@jebeck 

Quick text updates to the terms overlay for Blip. Copy is on the Trello card linked below.

Resolves: https://trello.com/c/ljrwYEP8

### CODE REVIEW

**Comment by jebeck** [comment]
@HowardLook is the non-standard capitalization in "I Agree to these Terms" really intended? Just wanted to double-check. Otherwise, LGTM.

**Comment by HowardLook** [comment]
"I agree to these terms" is fine, too, but also OK to push to prod as is
and fix later.

H

**Comment by jebeck** [comment]
Since I asked for an additional fix on #201, @ursooperduper should be able to change the capitalization before we pull in another batch of blip stuff to be tested for prod.

**Comment by ursooperduper** [comment]
@jebeck @HowardLook I will make that capitalization change now. I took the capitalization as it is now from the approved updated copy, so I assumed it had been reviewed and was supposed to be that way.

**Pull request merged**
